### PR TITLE
WP UI RTL support

### PR DESCRIPTION
**Pull request by debbieellis7**
## Description

Issue: #1208

RTL languages like Arabic and Hebrew put WordPress admin in RTL mode, where everything is reversed. All functionality should work as expected under WP RTL mode.

## Checklist:
- [x] I've tested the code.
- [x] My code is easy to read, follow, and understand
- [ ] My code follows the accessibility standards. 
- [x] My code has proper inline documentation / docblocks.

### CODE REVIEW

**Review by jakejackson1 — CHANGES_REQUESTED** [review]
Overall, it's looking pretty good! Here's some minor issues I spotted:

**Global Settings Page: The radio buttons and their associated labels are out of whack:**
Screen Shot 2021-03-11 at 3 02 02 pm

**Form PDF List Page: Status icon padding off**
Screen Shot 2021-03-11 at 3 05 04 pm

**Form PDF Add/Update Page: Background Image input box issue**
Screen Shot 2021-03-11 at 3 08 02 pm

**Form PDF Add/Update Page: Format radio button display issue**
Screen Shot 2021-03-11 at 3 09 16 pm

**Comment by jakejackson1** [comment]
@debbieellis7 I tested this out again, but couldn't see any fixes in relation to the four screenshots shown here: https://github.com/GravityPDF/gravity-pdf/pull/1212#pullrequestreview-609380078

Could you please double check your work?

**Comment by debbieellis7** [comment]
> @debbieellis7 I tested this out again, but couldn't see any fixes in relation to the four screenshots shown here: [#1212 (review)](https://github.com/GravityPDF/gravity-pdf/pull/1212#pullrequestreview-609380078)
> 
> Could you please double check your work?

Try clear your browser history @jakejackson1.

**Comment by jakejackson1** [comment]
@debbieellis7 could you add screenshots of the fixes on your end so I know what I should be seeing please?

**Comment by debbieellis7** [comment]
> @debbieellis7 could you add screenshots of the fixes on your end so I know what I should be seeing please?

**Comment by jakejackson1** [comment]
@debbieellis7 thanks. I was able to get it working now. 

I dislike that the radio button fix is hardcoded to specific settings, as the problem will occur on any radio buttons in the Template tab that a template might register. 

Screen Shot 2021-03-18 at 9 17 15 pm

Also, the labels for the radio buttons aren't matching up with the checkboxes. For example, in the Advanced section if you click on the "Standard" option you would expect the radio button directly to the right would be selected, and not the far right like it is currently doing.

Screen Shot 2021-03-18 at 9 19 14 pm

Let's look at how we can fix both problems without directly targeting specific IDs.

**Comment by debbieellis7** [comment]
@jakejackson1 , I believe I've just fixed the issues you mentioned. Please double check. Thanks!

**Pull request merged**
