### PR TITLE
Add End to End testing with Test Cafe

### PR DESCRIPTION
**Pull request by debbieellis7**
## Description

Issue: #915 
Test all our UI components to ensure consistency when making changes.

## Testing instructions
1. Start Docker. Note: if running Local By Flywheel, first run `docker-machine start`, then `docker-machine env` and run the command that gets spit out to configure your shell e.g `eval $(docker-machine env)`.
2. Copy `.env.example` to `.env` and replace `0000000000000000` with a valid Elite license key in `.env`
3. Run `./bin/setup-local-env.sh` from the command line
4. Run `yarn run test:e2e` / `yarn run test:e2e:headless`

## Checklist:
- [x] I've tested the code.
- [x] My code is easy to read, follow, and understand
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation / docblocks.

### CODE REVIEW

**Comment by debbieellis7** [comment]
[gravityform.zip](https://github.com/GravityPDF/gravity-pdf/files/3444698/gravityform.zip)
Gravity Form

**Comment by jakejackson1** [comment]
@debbieellis7 I think we should look at refractoring the tests with the Page Model https://devexpress.github.io/testcafe/documentation/recipes/extract-reusable-test-code/use-page-model.html, and if needed Helpers https://devexpress.github.io/testcafe/documentation/recipes/extract-reusable-test-code/create-helpers.html

**Comment by jakejackson1** [comment]
@debbieellis7 we should also impliment Live Mode as a Yarn script to make it easier for development https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/live-mode.html

**Comment by jakejackson1** [comment]
@debbieellis7 I've just added a pre-load data feature for Docker. When you run `./bin/setup-local-env.sh` it'll automatically add 5 forms with 1 entry each. I'm currently doing this with the WPCLI, but it may be faster to do a DB dump and importing the GF tables in one command. Will need to test this some more later.

**Comment by jakejackson1** [comment]
Running the whole E2E testing suite can take time, so I'd like to limit its usage to the `master` and `development`. To streamline this, I'll need to rewrite the Travis CI config and [implement build stages](https://docs.travis-ci.com/user/build-stages/). [I'll handle this at the same time as configuring Travis to run the E2E suite](https://devexpress.github.io/testcafe/documentation/continuous-integration/travis.html).

**Comment by jakejackson1** [comment]
I've found a lot of issues using Chrome to run the E2E tests (both in standard and headless modes). I think it would be a good idea to swap over to FireFox, which is running like a dream.

**Comment by jakejackson1** [comment]
@debbieellis7 FYI, on my machine the following tests are failing:

 × should open 'Add Font Dialog Box Settings' that can be close
 × should open 'Setup Custom Templates' popup box

**Comment by jakejackson1** [comment]
Some other advanced checks

- Gravity PDF shortcode works on all 3 confirmation types
- same with the merge tags
- debug mode shows shortcode error when PDF inactive, or no link when debug off
- PDF cannot be accessed by logged out user (error thrown)
- PDF cannot be accessed by non administrator user

**Comment by debbieellis7** [comment]
> @debbieellis7 FYI, on my machine the following tests are failing:
> 
> × should open 'Add Font Dialog Box Settings' that can be close
> × should open 'Setup Custom Templates' popup box

Fixed!

**Comment by debbieellis7** [comment]
> I've found a lot of issues using Chrome to run the E2E tests (both in standard and headless modes). I think it would be a good idea to swap over to FireFox, which is running like a dream.

What issues @jakejackson1 ?

**Comment by debbieellis7** [comment]
Unable perform testcafe font upload/installation under (Tools --> Manage Fonts) input type needs to be file (<input type="file" />) @jakejackson1

**Comment by debbieellis7** [comment]
mpdf need to be configure to use core fonts for the confirmation shortcode test.

current error screenshots:

**Comment by debbieellis7** [comment]
Bug - PDF General Settings not updating new values in 1st attempt. @jakejackson1 

Need to add 1 new user with non-administrator role.
username - user
password - password

**Comment by jakejackson1** [comment]
@debbieellis7 I've fixed the general settings bug. Just fetch all from the remote and you should be good to go.

Will get the user tomorrow for you.

**Comment by jakejackson1** [comment]
Need to look into possibility of using Circle CI for the E2E testing:
https://devexpress.github.io/testcafe/documentation/continuous-integration/circleci.html

**Pull request merged**
