### PR TITLE
Updating JS dependencies [R2]

### PR DESCRIPTION
**Pull request by debbieellis7**
Updating JS main dependencies

### CODE REVIEW

**Comment by debbieellis7** [comment]
'superagent' dependency is updated up to '3.8.3' only as higher version require configuration in webpack/babel thing which I'm not sure how exactly do it.

**Comment by debbieellis7** [comment]
'superagent' dependency is updated up to '3.8.3' only as higher version require configuration in webpack/babel thing which I'm not sure how exactly do it.

reference link: https://libupdate.com/libs/d391b3a2-36fa-474e-a8a1-641a28f2a8d6

**Comment by debbieellis7** [comment]
'superagent' dependency is updated up to '3.8.3' only as higher version require configuration in webpack/babel thing which I'm not sure how exactly do it.

reference link: https://libupdate.com/libs/d391b3a2-36fa-474e-a8a1-641a28f2a8d6

**Comment by debbieellis7** [comment]
I leave 'immutable' dependency untouched as we are going to remove it in #728

**Comment by jakejackson1** [comment]
> 'superagent' dependency is updated up to '3.8.3' only as higher version require configuration in webpack/babel thing which I'm not sure how exactly do it.

We already use Webpack and Babel for building our JavaScript. Based on the changelogs I can't see any obvious changes we would need to make. Did you try upgrade to superagent v4 and see if it worked? If it didn't, what errors are you getting?

**Comment by debbieellis7** [comment]
> > 'superagent' dependency is updated up to '3.8.3' only as higher version require configuration in webpack/babel thing which I'm not sure how exactly do it.
> 
> We already use Webpack and Babel for building our JavaScript. Based on the changelogs I can't see any obvious changes we would need to make. Did you try upgrade to superagent v4 and see if it worked? If it didn't, what errors are you getting?

Yes. taking a screenshot of it now.

**Comment by debbieellis7** [comment]
> @debbieellis7 could we fix up this notice in the console please:
> 
> `window.devToolsExtension is deprecated in favor of window.__REDUX_DEVTOOLS_EXTENSION__, and will be removed in next version of Redux DevTools: https://git.io/fpEJZ`
> 
> Everything else looks good.

Yeah I forgot it. I was about to do it in the last part.

**Comment by debbieellis7** [comment]
@jakejackson1 Redux devtools deprecation issue is fixed now.

**Comment by jakejackson1** [comment]
@saggonzales can you pull down this fork, rebuild the JS (`yarn run build`, `gulp`) and then test all the JS-based features in the plugin (talk with @debbieellis7 if you aren't sure what pages this all exists on).

Thanks!

**Pull request merged**
